services:
    report-api:
        image: ghcr.io/mata-elang-stable/report-api-services:latest
        build: .
        depends_on:
            pgsql:
                condition: service_healthy
            redis:
                condition: service_healthy
            chromium:
                condition: service_started
            web:
                condition: service_started
        env_file:
            - .env
        volumes:
            - report_data:/var/www/html/
        deploy:
            restart_policy:
                condition: on-failure
                delay: 15s
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G

    web:
        image: nginx:alpine
        restart: unless-stopped
        ports:
        - "8085:80"
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - report_data:/var/www/html/:ro

    chromium:
        image: zenika/alpine-chrome
        command: [ chromium-browser, "--headless", "--disable-gpu", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222", "--no-sandbox", "--disable-dev-shm-usage"]
        cap_add:
            - SYS_ADMIN
        ports:
            - '9222:9222'
        networks:
            - sail

    pgsql:
        image: 'postgres:17'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
    report_data:
        driver: local
